![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [208]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.20.1


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [209]:
# your code goes here


In [210]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [211]:
# your code goes here


In [212]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [213]:
# your code goes here


In [214]:
np.ones([2,2], dtype=np.int)

<ipython-input-214-b2fe104d15dd>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [215]:
# your code goes here


In [216]:
np.ones([3,2], dtype=np.float)

<ipython-input-216-06da4d8ebb5c>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [217]:
# your code goes here


In [218]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

<ipython-input-218-92475a07ca52>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype=np.int)


array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [219]:
# your code goes here


In [220]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

<ipython-input-220-5fd7486fee45>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1,2,3], [4,5,6]], dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [221]:
# your code goes here


In [222]:
np.ones([4,4], dtype=np.int) * 5

<ipython-input-222-2a5e1177b148>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [223]:
# your code goes here


In [224]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

<ipython-input-224-120c34b82896>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[2,3], [6,2]], dtype=np.int)


array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [225]:
# your code goes here

In [226]:
#np.eye(3)
np.identity(2)

array([[1., 0.],
       [0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [227]:
# your code goes here


In [228]:
np.random.randint(10,size=3)

0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [229]:
# your code goes here


In [230]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 0.08317206,  0.1416253 ,  0.07410357],
        [ 1.0467923 , -0.7851535 ,  1.28814006],
        [ 0.09994711, -1.31620482,  1.13624774]],

       [[ 0.04489786,  1.42050968, -0.51644897],
        [-1.20417079,  0.13228867, -0.42101417],
        [ 1.23809999,  0.57593152, -0.40540672]],

       [[-0.19986471, -2.30948659, -0.3426719 ],
        [-0.15479083, -2.61572405,  1.08338545],
        [-2.40484044,  1.54284971, -0.1726776 ]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [231]:
# your code goes here


In [232]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [233]:
# your code goes here


In [234]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 2451347023216
[5 2 3] 2451347022928


<ipython-input-234-c47ff8a1a6fa>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([5,2,3], dtype=np.int)


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [235]:
# your code goes here


In [236]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [237]:
# your code goes here


In [238]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [239]:
# your code goes here


In [240]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [241]:
# your code goes here


In [242]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [243]:
# your code goes here


In [244]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [245]:
# your code goes here


In [246]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [247]:
# your code goes here


In [248]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [249]:
# your code goes here


In [250]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [251]:
# your code goes here


In [252]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [253]:
# your code goes here


In [254]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [255]:
# your code goes here


In [256]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [257]:
# your code goes here


In [258]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [259]:
# your code goes here


In [260]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [261]:
# your code goes here


In [262]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [263]:
# your code goes here


In [264]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [265]:
# your code goes here


In [266]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [267]:
# your code goes here


In [268]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [269]:
# your code goes here


In [270]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [271]:
# your code goes here


In [272]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

<ipython-input-272-0804978484f1>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [273]:
# your code goes here


In [274]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [275]:
# your code goes here


In [276]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [277]:
# your code goes here


In [278]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [279]:
# your code goes here


In [280]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [281]:
# your code goes here


In [282]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [283]:
# your code goes here


In [284]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [285]:
# your code goes here


In [286]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [287]:
# your code goes here


In [288]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [289]:
# your code goes here


In [290]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [291]:
# your code goes here


In [292]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [293]:
# your code goes here


In [294]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [295]:
# your code goes here


In [296]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [297]:
# your code goes here


In [298]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [299]:
# your code goes here


In [300]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [301]:
# your code goes here


In [302]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [303]:
# your code goes here


In [304]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [305]:
# your code goes here


In [306]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [307]:
# your code goes here


In [308]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [309]:
# your code goes here


In [310]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)